// <auto-generated />
namespace DriveMe.DAL.Migrations.Trip
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class UserInitial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserInitial));
        
        string IMigrationMetadata.Id
        {
            get { return "201605131436223_UserInitial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
