// <auto-generated />
namespace DriveMe.DAL.Migrations.Trip
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddTripRef : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddTripRef));
        
        string IMigrationMetadata.Id
        {
            get { return "201605271549466_Add Trip Ref"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
