// <auto-generated />
namespace DriveMe.DAL.Identity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class UserInheritance : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserInheritance));
        
        string IMigrationMetadata.Id
        {
            get { return "201603221059143_UserInheritance"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
