// <auto-generated />
namespace DriveMe.DAL.Identity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RoutesParameters : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RoutesParameters));
        
        string IMigrationMetadata.Id
        {
            get { return "201603240829141_RoutesParameters"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
